name: Build Docker Image
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t europe-west6-docker.pkg.dev/csquare/public-examples/mnist-horovod-example:latest .
      - name: Setup Google Cloud SDK
        uses: mathieu-bour/setup-gcloud@1.3.0
        with:
          version: local
          service-account-key: ${{ secrets.GCLOUD_AUTH }}
          configure-docker: europe-west6-docker.pkg.dev
      - name: Push Docker Image to Google Artifact Registry
        run: docker push europe-west6-docker.pkg.dev/csquare/public-examples/mnist-horovod-example:latest
